---

- name: DOCKER TASK | Add GPG key [Ubuntu]
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: DOCKER TASK | Add Docker repo [Ubuntu]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: DOCKER TASK | Add Docker repo [Debian]
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_distribution == 'Debian'

- name: DOCKER TASK | Install Docker packages [Ubuntu]
  apt:
    name: "{{ docker_packages_ubuntu }}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: DOCKER TASK | Install Docker packages [Debian]
  apt:
    name: "{{ docker_packages_debian }}"
    state: present
    update_cache: yes
  when: ansible_distribution == 'Debian'

- name: DOCKER TASK | Download Docker-Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  when: docker_compose_version is defined
